---
title: "Analysis"
author: "Matthew Loder"
date: "7/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cleaning scripts:
```{r packages, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(gridExtra)
library(DescTools)
library(splines)
library(stringr)
source("helpers.R")


theme_set(theme_bw())

colscale = scale_color_manual(values=c("#7CB637", "#666666", "#4381C1")) 
colscale_fill = scale_fill_manual(values=c("#7CB637", "#666666", "#4381C1")) 

remove_quotes = function(d) {
  
}

format_data = function(d) {
  drops <- c("modal1","rating1")
  d2 = d[ , !(names(d) %in% drops)]
  setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))
  
  drops <- c("modal2","rating2")
  d3 = d[ , !(names(d) %in% drops)]
  setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))
  
  drops <- c("modal2", "rating2", "modal1", "rating1")
  d4 = d[ , !(names(d) %in% drops)]
  d4$rating = d4$rating_other
  d4$modal = "other"
  
  d = rbind(d2, d3, d4)
  
  d$modal = gsub('"', '', d$modal)
  d$modal = factor(d$modal, levels = c("might", "probably", "other"), ordered = T)
  
  d$percent_window_f = factor(d$percent_window)
  
  d_aisle = d %>% filter(.,grepl("aisle", type))
  d_window = d %>% filter(.,grepl("window", type))
  
  d_aisle_reverse = d_aisle
  d_aisle_reverse$percent_window = 100-d_aisle$percent_window
  
  d_comparison = rbind(d_window, d_aisle_reverse)
  d_comparison$percent_window_f = factor(d_comparison$percent_window)
  
  return(d_comparison)
}

```

## Load data:

```{r data, echo=FALSE}
trials_cond1 = format_data(read.csv("../data/02_norming_cond1-trials.csv"))
trials_cond2 = format_data(read.csv("../data/02_norming_cond2-trials.csv"))

d1 = trials_cond1
d2 = trials_cond2

# combine data: 
d1$Answer.condition = "optimist"
d2$Answer.condition = "pessimist"
```

## Exclude random responses
```{r}
d_overall_means = d1 %>%
  group_by(modal, workerid) %>% 
  summarise(rating_m_overall = mean(rating))

d_indiv_means =  d1 %>%
  group_by(modal,percent_window, workerid) %>% 
  summarise(rating_m = mean(rating))

d_indiv_merged = merge(d_indiv_means, d_overall_means, by=c("workerid", "modal"))

cors = d_indiv_merged %>%
  group_by(workerid) %>%
  summarise(corr = cor(rating_m, rating_m_overall))

exclude = cors %>%
  filter(corr > 0.75) %>%
  .$workerid

print(paste("Excluded", length(exclude), "participants based on random responses."))

d1 = d1 %>% filter(!(workerid %in% exclude))
```

```{r}
d_overall_means = d2 %>%
  group_by(modal, workerid) %>% 
  summarise(rating_m_overall = mean(rating))

d_indiv_means =  d2 %>%
  group_by(modal,percent_window, workerid) %>% 
  summarise(rating_m = mean(rating))

d_indiv_merged = merge(d_indiv_means, d_overall_means, by=c("workerid", "modal"))

cors = d_indiv_merged %>%
  group_by(workerid) %>%
  summarise(corr = cor(rating_m, rating_m_overall))

exclude = cors %>%
  filter(corr > 0.75) %>%
  .$workerid

print(paste("Excluded", length(exclude), "participants based on random responses."))

d2 = d2 %>% filter(!(workerid %in% exclude))
```

## Aggregated results

```{r aggregate_plots, echo=FALSE, fig.width=10, fig.height=8}
plot_conditions = function(d, plot_title) {
  d_means = d %>%
    group_by(workerid, percent_window, modal) %>%
    summarise(participant_mean = mean(rating)) %>%
    group_by(percent_window, modal) %>%
    summarise(mu = mean(participant_mean),
              ci_high = ci.high(participant_mean),
              ci_low = ci.low(participant_mean))

  p1 = ggplot(d_means, aes(x = percent_window, y = mu, col=modal)) + 
    xlab("% preferred seating") +
    ylab("mean ratings") +
    geom_errorbar(aes(ymin=mu-ci_low, ymax=mu+ci_high), width=.1) +
    geom_line() +
    geom_point(size=1) +
    guides(col=guide_legend(title="Expr.")) +
    colscale +
    theme(legend.position="bottom") + 
    ggtitle(plot_title) 
  
  p2 = ggplot(d, aes(x=percent_window_f, y=rating, fill=modal)) + 
    geom_boxplot() +
    ggtitle(plot_title) + xlab("percentage") + colscale_fill +   theme(legend.position="bottom")
  
  by_participant = ggplot( d %>%
    group_by(workerid, percent_window, modal) %>% 
    summarise(participant_mean = mean(rating)) , 
      aes(x=percent_window, y=participant_mean, col=modal)
        ) + 
    xlab("% preferred seat") +
    ylab("mean ratings") +
    geom_line() +
    geom_point(size=1) +
    guides(col=guide_legend(title="Expr.")) +
    colscale +
    theme(legend.position="bottom") + ggtitle(plot_title) + facet_wrap(~workerid, ncol = 8)
    return(list("p1" = p1, "p2" = p2, "by_participant" = by_participant))
}


ps1 = plot_conditions(d1, "")
ps2 = plot_conditions(d2, "")

plot(ps1$p1)
plot(ps2$p1)
```
## Individual plots

```{r by_participant_plots}
plot(ps1$by_participant)
plot(ps2$by_participant)
```

## AUC Computation

```{r auc_method_1, echo=FALSE}

auc_method1 = function(d) {
      #estimate linear model
    model = lm(formula = rating_m ~ ns(percent_window, df = 4), data = d)
  
    pred = data.frame(0:1000)
    pred$percent_window = (0:1000)/10
    pred$rating = predict(model, pred)
    auc = AUC(x = pred$percent_window, y=pred$rating)
    return(auc)
}

auc_for_participants = function(d, method) {
  
  aucs = d %>% 
    group_by(workerid) %>%
    summarize(auc_might = 0, auc_probably = 0)
  
i = 1

  for (wid in unique(d$workerid)) {
    d.might_ratings = d %>% 
      filter (workerid == wid) %>%
      filter (modal == "might") %>%
      group_by(workerid, percent_window) %>%
      summarise(rating_m = mean(rating))
    
    aucs$auc_might[i] = method(d.might_ratings)
    
    d.probably_ratings = d %>% 
      filter (workerid == wid) %>%
      filter (modal == "probably") %>%
      group_by(workerid, percent_window) %>%
      summarise(rating_m = mean(rating))
    
    aucs$auc_probably[i] = method(d.probably_ratings)
    i = i + 1
  }
  
  aucs$auc_diff = aucs$auc_might - aucs$auc_probably
  
  return(aucs)
}

aucs.optimist = d1 %>% auc_for_participants(., method=auc_method1)

aucs.pessimist = d2 %>% auc_for_participants(., method=auc_method1)

aucs.optimist$cond = "Optimistic condition"

aucs.pessimist$cond = "Pessimistic condition"

aucs.all = rbind(aucs.optimist, aucs.pessimist)

aucs.all = aucs.all %>% 
  group_by(., cond) %>% 
  summarise(., auc_diff_m = mean(auc_diff), 
               ci_high = ci.high(auc_diff), 
               ci_low = ci.low(auc_diff))

ggplot(aucs.all, aes(x=0, y=auc_diff_m, color=cond)) +
    geom_errorbar(aes(ymin=auc_diff_m-ci_low, ymax=auc_diff_m+ci_high), width=.1) +
    geom_point() +
    xlab("") +
    ylab("AUC difference (might ratings - probably ratings)") +
    theme(axis.ticks=element_blank(), axis.text.x=element_blank(),
          panel.grid.minor=element_blank(), 
          plot.background=element_blank()) +
    xlim(-.2, .2) 
```

```{r t_test_method1, echo=FALSE}

print(t.test(aucs.optimist$auc_diff, aucs.pessimist$auc_diff, var.equal=TRUE))

```

