---
title: "Analysis of norming experiment"
author: "Sebastian Schuster"
date: "1/20/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
theme_set(theme_bw())
library(DescTools)
library(splines)


auc_method = function(rating, response_m) {
  d = data.frame(rating = rating, response_m = response_m)
  model = lm(formula = response_m ~ ns(rating, df = 4), data = d)
  
  pred = data.frame(100:600)
  pred$rating = (100:600)/100
  pred$response = predict(model, pred)
  
  auc = AUC(x = pred$rating, y=pred$response)
  return(auc)
}

```

```{r load_data, fig.width=10, echo=FALSE}

d.neutral = read.csv("../data/09_evaluative_adj_norming-pilot-cond1-trials.csv")
d.friend = read.csv("../data/09_evaluative_adj_norming-pilot-cond2-trials.csv")
d.friend$workerid = d.friend$workerid + max(d.neutral$workerid) + 1
d.enemy = read.csv("../data/09_evaluative_adj_norming-pilot-cond3-trials.csv")
d.enemy$workerid = d.enemy$workerid + max(d.friend$workerid) + 1

d = rbind(d.neutral, d.friend, d.enemy)

d = d %>% filter(trial_type == "trial")



d.indiv = d %>%
  group_by(rating, workerid, adjective, condition) %>% 
  dplyr::summarize(mu = mean(response)) %>%ungroup()

d.amazing.6 = d.indiv %>% filter(rating == 6) %>% filter(adjective == "amazing") %>% select(mu, workerid, condition)  %>% dplyr::rename(amazing6_response = mu) 
d.terrible.1 = d.indiv %>% filter(rating == 1) %>% filter(adjective == "terrible") %>% select(mu, workerid, condition) %>% dplyr::rename(terrible1_response = mu) 
d.amazing.1 = d.indiv %>% filter(rating == 1) %>% filter(adjective == "amazing") %>% select(mu, workerid, condition) %>% dplyr::rename(amazing1_response = mu) 
d.terrible.6 = d.indiv %>% filter(rating == 1) %>% filter(adjective == "terrible") %>% select(mu, workerid, condition) %>% dplyr::rename(terrible6_response = mu) 



exclude.workers = merge(d.amazing.6, d.terrible.1, by=c("workerid", "condition")) %>% 
  merge(d.terrible.6, by=c("workerid", "condition")) %>%
  merge(d.amazing.1, by=c("workerid", "condition")) %>%
  filter(amazing6_response < .4 | amazing1_response > .15) %>% 
  filter(terrible1_response < .4 | terrible6_response > .15) %>% 
  .$workerid

d.excluded = d %>% filter((workerid %in% exclude.workers))

d = d %>% filter(!(workerid %in% exclude.workers))

d.avg = d %>% 
  group_by(rating, adjective, condition) %>% 
  dplyr::summarize(mu = mean(response), ci.lower = ci.low(response), ci.upper=ci.high(response))


d.avg %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~condition)

d.avg %>% ggplot(aes(x=rating, fill=adjective, y=mu))  + xlim(1,6) + facet_wrap(~condition) + geom_area()

d.avg %>% ggplot(aes(x=rating, col=condition, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~adjective)

d.aucs = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(auc = auc_method(rating, response_m)) %>%
  mutate(adjective_grpd = stringr::str_replace(adjective, "terrible", "bad")) %>%
  mutate(adjective_grpd =  stringr::str_replace(adjective_grpd, "amazing", "good")) %>%
  group_by(adjective_grpd, condition, workerid) %>% 
  dplyr::summarize(auc = sum(auc))

d.bad = d.aucs %>% filter(adjective_grpd == "bad") %>% dplyr::rename(auc.bad = auc)
d.good = d.aucs %>% filter(adjective_grpd == "good") %>%  dplyr::rename(auc.good = auc)

d.auc.comb = merge(d.bad, d.good, by=c("workerid", "condition")) %>% mutate(auc.diff = auc.good - auc.bad)

d.auc.comb %>% group_by(condition) %>% 
  dplyr::summarize(auc.diff_m = mean(auc.diff), 
                   ci.lower = ci.low(auc.diff), 
                   ci.upper=ci.high(auc.diff)) %>% 
  ggplot(aes(y = auc.diff_m, col=condition, x=0)) + geom_point(size=5) + 
  geom_errorbar(aes(ymin=auc.diff_m-ci.lower, ymax=auc.diff_m+ci.upper)) + xlim(-2,2) + ylab("AUC (good + amazing) - AUC (bad + terrible)")

d.norm = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::mutate(response_norm = response_m / (sum(response_m) + 0.001)) %>%
  dplyr::mutate(rating_weighted = response_norm * (rating -1 )) %>%
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(expected_rating = sum(rating_weighted))

d.norm %>% 
  group_by(adjective, condition) %>%
  dplyr::summarize(mu = mean(expected_rating), ci.lower = ci.low(expected_rating), ci.upper=ci.high(expected_rating)) %>%
  ggplot(aes(x=adjective, y=mu, col=condition)) + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=mu+ci.upper))



```


### Per-participant plots


```{r per_participant, fig.width=10, fig.height=30, echo=FALSE}

d.part = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(mu = mean(response))

d.part %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() +  xlim(1,6) + facet_wrap(~condition + workerid, ncol=5) +
  theme(legend.position = "bottom")

```

## Per-participant plots for excluded participants

```{r per_participant_excluded, fig.width=10, fig.height=15, echo=FALSE}

d.part.excluded = d.excluded %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(mu = mean(response))

d.part.excluded %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() +  xlim(1,6) + facet_wrap(~condition + workerid, ncol=5) +
  theme(legend.position = "bottom")

```

### Statistical tests (AUC difference)

```{r t_test, echo=FALSE}

d.friends.diffs = d.auc.comb %>% filter(condition == "friends") %>% .$auc.diff
d.enemy.diffs = d.auc.comb %>% filter(condition == "enemy") %>% .$auc.diff

t.test(d.friends.diffs, d.enemy.diffs, var.equal = TRUE)

```

### Statistical tests (difference in expected rating)


```{r t_tests2, echo=FALSE}


expressions = c("terrible", "bad", "good", "okay", "amazing")

for (expr in expressions) {
     print(expr)
     vals.friend = d.norm %>% filter(adjective == expr) %>% filter(condition == "friends") %>% .$expected_rating
     vals.enemy = d.norm %>% filter(adjective == expr) %>% filter(condition == "enemy") %>% .$expected_rating
     print(t.test(vals.friend, vals.enemy, var.equal = TRUE))
}

```

