---
title: "Analysis of norming experiment"
author: "Sebastian Schuster"
date: "1/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
theme_set(theme_bw())
library(DescTools)
library(splines)


auc_method = function(rating, response_m) {
  d = data.frame(rating = rating, response_m = response_m)
  model = lm(formula = response_m ~ ns(rating, df = 4), data = d)
  
  pred = data.frame(100:600)
  pred$rating = (100:600)/100
  pred$response = predict(model, pred)
  
  auc = AUC(x = pred$rating, y=pred$response)
  return(auc)
}

```

```{r load_data, fig.width=10}

d.neutral = read.csv("../data/09_evaluative_adj_norming-pilot-cond1-trials.csv")
d.friend = read.csv("../data/09_evaluative_adj_norming-pilot-cond2-trials.csv")
d.enemy = read.csv("../data/09_evaluative_adj_norming-pilot-cond3-trials.csv")

d = rbind(d.neutral, d.friend, d.enemy)

d = d %>% filter(trial_type == "trial")

d.avg = d %>% 
  group_by(rating, adjective, condition) %>% 
  dplyr::summarize(mu = mean(response), ci.lower = ci.low(response), ci.upper=ci.high(response))



d.avg %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~condition)

d.avg %>% ggplot(aes(x=rating, fill=adjective, y=mu))  + xlim(1,6) + facet_wrap(~condition) + geom_area()

d.avg %>% ggplot(aes(x=rating, col=condition, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~adjective)

d.aucs = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(auc = auc_method(rating, response_m)) %>%
  mutate(adjective_grpd = stringr::str_replace(adjective, "terrible", "bad")) %>%
  mutate(adjective_grpd =  stringr::str_replace(adjective_grpd, "amazing", "good")) %>%
  group_by(adjective_grpd, condition, workerid) %>% 
  dplyr::summarize(auc = sum(auc))



d.bad = d.aucs %>% filter(adjective_grpd == "bad") %>% dplyr::rename(auc.bad = auc)
d.good = d.aucs %>% filter(adjective_grpd == "good") %>%  dplyr::rename(auc.good = auc)

d.auc.comb = merge(d.bad, d.good, by=c("workerid", "condition")) %>% mutate(auc.diff = auc.good - auc.bad)

d.auc.comb %>% group_by(condition) %>% 
  dplyr::summarize(auc.diff_m = mean(auc.diff), 
                   ci.lower = ci.low(auc.diff), 
                   ci.upper=ci.high(auc.diff)) %>% 
  ggplot(aes(y = auc.diff_m, col=condition, x=0)) + geom_point(size=5) + 
  geom_errorbar(aes(ymin=auc.diff_m-ci.lower, ymax=auc.diff_m+ci.upper)) + xlim(-2,2) + ylab("AUC (good + amazing) - AUC (bad + terrible)")



d.norm = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::mutate(response_norm = response_m / sum(response_m)) %>%
  dplyr::mutate(rating_weighted = response_norm * rating) %>%
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(expected_rating = sum(rating_weighted))

d.norm %>% 
  group_by(adjective, condition) %>%
  dplyr::summarize(mu = mean(expected_rating), ci.lower = ci.low(expected_rating), ci.upper=ci.high(expected_rating)) %>%
  ggplot(aes(x=adjective, y=mu, col=condition)) + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=mu+ci.upper))

```
```{r per_part, fig.width=10, fig.height=10}

d.part = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(mu = mean(response))

d.part %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() +  xlim(1,6) + facet_wrap(~condition + workerid, ncol=5)


```

```{r plots_2, fig.width=10}

d.neutral = read.csv("../data/09_evaluative_adj_norming-pilot-cond1a-trials.csv")
d.friend = read.csv("../data/09_evaluative_adj_norming-pilot-cond2a-trials.csv")
d.enemy = read.csv("../data/09_evaluative_adj_norming-pilot-cond3a-trials.csv")

d = rbind(d.neutral, d.friend, d.enemy)

d = d %>% filter(trial_type == "trial")

d.avg = d %>% 
  group_by(rating, adjective, condition) %>% 
  dplyr::summarize(mu = mean(response), ci.lower = ci.low(response), ci.upper=ci.high(response))

d.avg %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~condition)

d.avg %>% ggplot(aes(x=rating, fill=adjective, y=mu))  + xlim(1,6) + facet_wrap(~condition) + geom_area()

d.avg %>% ggplot(aes(x=rating, col=condition, y=mu)) + geom_line() + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=ci.upper+mu)) + xlim(1,6) + facet_wrap(~adjective)



d.aucs = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(auc = auc_method(rating, response_m)) %>%
  mutate(adjective_grpd = stringr::str_replace(adjective, "terrible", "bad")) %>%
  mutate(adjective_grpd =  stringr::str_replace(adjective_grpd, "amazing", "good")) %>%
  group_by(adjective_grpd, condition, workerid) %>% 
  dplyr::summarize(auc = sum(auc))

d.bad = d.aucs %>% filter(adjective_grpd == "bad") %>% dplyr::rename(auc.bad = auc)
d.good = d.aucs %>% filter(adjective_grpd == "good") %>%  dplyr::rename(auc.good = auc)

d.auc.comb = merge(d.bad, d.good, by=c("workerid", "condition")) %>% mutate(auc.diff = auc.good - auc.bad)

d.auc.comb %>% group_by(condition) %>% 
  dplyr::summarize(auc.diff_m = mean(auc.diff), 
                   ci.lower = ci.low(auc.diff), 
                   ci.upper=ci.high(auc.diff)) %>% 
  ggplot(aes(y = auc.diff_m, col=condition, x=0)) + geom_point(size=5) + 
  geom_errorbar(aes(ymin=auc.diff_m-ci.lower, ymax=auc.diff_m+ci.upper)) + xlim(-2,2) + ylab("AUC (good + amazing) - AUC (bad + terrible)")


d.norm = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(response_m = mean(response)) %>% 
  group_by(adjective, condition, workerid) %>% 
  dplyr::mutate(response_norm = response_m / (sum(response_m) + 0.001)) %>%
  dplyr::mutate(rating_weighted = response_norm * (rating -1 )) %>%
  group_by(adjective, condition, workerid) %>% 
  dplyr::summarize(expected_rating = sum(rating_weighted))

d.norm %>% 
  group_by(adjective, condition) %>%
  dplyr::summarize(mu = mean(expected_rating), ci.lower = ci.low(expected_rating), ci.upper=ci.high(expected_rating)) %>%
  ggplot(aes(x=adjective, y=mu, col=condition)) + geom_point() + geom_errorbar(aes(ymin=mu-ci.lower, ymax=mu+ci.upper))

expressions = c("terrible", "bad", "good", "okay", "amazing")

for (expr in expressions) {
     vals.friend = d.norm %>% filter(adjective == expr) %>% filter(condition == "friends") %>% .$expected_rating
     vals.enemy = d.norm %>% filter(adjective == expr) %>% filter(condition == "enemy") %>% .$expected_rating
     print(t.test(vals.friend, vals.enemy, var.equal = TRUE))
}

```


```{r per_part2, fig.width=10, fig.height=10}

d.part = d %>% 
  group_by(rating, adjective, condition, workerid) %>% 
  dplyr::summarize(mu = mean(response))

d.part %>% ggplot(aes(x=rating, col=adjective, y=mu)) + geom_line() + geom_point() +  xlim(1,6) + facet_wrap(~condition + workerid, ncol=5)


```

Power analysis

```{r power_analysis}

m.friend = mean(d.auc.comb %>% filter(condition == "friends") %>% .$auc.diff)
m.enemy = mean(d.auc.comb %>% filter(condition == "enemy") %>% .$auc.diff)

sd.friend = sd(d.auc.comb %>% filter(condition == "friends") %>% .$auc.diff)
sd.enemy = sd(d.auc.comb %>% filter(condition == "enemy") %>%  .$auc.diff)

eff_size = m.friend - m.enemy
eff_size= eff_size/sd.friend

power.t.test(n=40, delta=eff_size, sd=1, sig.level = 0.05, type="two.sample", alternative="two.sided")


# power analysis for expression comparison

vals.friend = d.norm %>% filter(adjective == "amazing") %>% filter(condition == "friends") %>% .$expected_rating
vals.enemy = d.norm %>% filter(adjective == "amazing") %>% filter(condition == "enemy") %>% .$expected_rating

m.friend = mean(vals.friend)
m.enemy = mean(vals.enemy)

sd.friend = sd(vals.friend)
sd.enemy = sd(vals.enemy)

eff_size = m.friend - m.enemy
eff_size= eff_size/sd.friend

power.t.test(n=40, delta=eff_size, sd=1, sig.level = 0.01, type="two.sample", alternative="two.sided")




```